services:
  api:
    image: 10.51.15.42:5000/maletas-api:latest
    container_name: maletas-api
    ports:
      - "3003:3003"
    restart: always
    networks:
      - maletas-net
    environment:
    #  POSTGRES_HOST: 10.51.15.101
      PORT: 3009

  app:
    image: 10.51.15.42:5000/maletas-ui:latest
    container_name: maletas-ui
    ports:
      - "8571:80"
    restart: always
    depends_on:
      - api
    networks:
      - maletas-net
    environment:
      API_URL: 'http://10.51.15.41:3009/'

networks:
  maletas-net:
    driver: bridge
    name: maletas-net
